### ISSUE TITLE
Error:format name 'markdown' is already taken

### ISSUE THREAD

**Issue by sunnycomes** [alminium/redmine_redcarpet_formatter#38]
> [ 2015-01-31 15:18:41.1383 30242/7f02d23bf700 Pool2/Implementation.cpp:287 ]: Could not spawn process for application /opt/redmine-2.6.1-1/apps/redmine/htdocs/: An error occured while starting up the preloader.
>   Error ID: fe342d49
>   Error details saved to: /tmp/passenger-error.keWIiS
>   Message from application: You cannot specify the same gem twice with different version requirements.
> You specified: redcarpet (~> 2.3.0) and redcarpet (>= 0) (Bundler::GemfileError)
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.0/lib/bundler/dsl.rb:84:in `gem'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/plugins/redmine_redcarpet_formatter/Gemfile:3:in`block in eval_gemfile'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/Gemfile:109:in `instance_eval'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/Gemfile:109:in`block in eval_gemfile'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/Gemfile:106:in `glob'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/Gemfile:106:in`eval_gemfile'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.0/lib/bundler/dsl.rb:32:in `instance_eval'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.0/lib/bundler/dsl.rb:32:in`eval_gemfile'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.0/lib/bundler/dsl.rb:10:in `evaluate'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.0/lib/bundler/definition.rb:25:in`build'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.0/lib/bundler.rb:154:in `definition'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.0/lib/bundler.rb:117:in`setup'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/bundler-1.7.0/lib/bundler/setup.rb:17:in `<top (required)>'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in`require'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in`require'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/lib/phusion_passenger/loader_shared_helpers.rb:263:in `block in run_load_path_setup_code'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/lib/phusion_passenger/loader_shared_helpers.rb:366:in`running_bundler'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/lib/phusion_passenger/loader_shared_helpers.rb:261:in `run_load_path_setup_code'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:100:in`preload_app'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:158:in `<module:App>'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:29:in`module:PhusionPassenger'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:28:in `<main>'

So I updated Gemfile, change `gem "redcarpet"` to `gem "redcarpet", "~>2.3.0"`, but another error occurs:

> [ 2015-01-31 15:24:57.0850 30916/7f04509d2700 Pool2/Implementation.cpp:287 ]: Could not spawn process for application /opt/redmine-2.6.1-1/apps/redmine/htdocs/: An error occured while starting up the preloader.
>   Error ID: 935034bc
>   Error details saved to: /tmp/passenger-error.EhBsZF
>   Message from application: format name 'markdown' is already taken (ArgumentError)
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/lib/redmine/wiki_formatting.rb:33:in `register'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/lib/redmine/plugin.rb:361:in`wiki_format_provider'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/plugins/redmine_redcarpet_formatter/init.rb:29:in `block in <top (required)>'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/lib/redmine/plugin.rb:75:in`instance_eval'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/lib/redmine/plugin.rb:75:in `register'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/plugins/redmine_redcarpet_formatter/init.rb:23:in`<top (required)>'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in`block in require'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in`require'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/lib/redmine/plugin.rb:150:in `block in load'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/lib/redmine/plugin.rb:141:in`each'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/lib/redmine/plugin.rb:141:in `load'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/config/initializers/30-redmine.rb:19:in`<top (required)>'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in`block in load'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in`load'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/engine.rb:592:in`each'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/engine.rb:592:in `block in <class:Engine>'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/initializable.rb:30:in`instance_exec'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/initializable.rb:55:in`block in run_initializers'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/initializable.rb:54:in`run_initializers'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in`method_missing'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
>   config.ru:3:in`require'
>   config.ru:3:in `block in <main>'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in`instance_eval'
>   /opt/redmine-2.6.1-1/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
>   config.ru:1:in`new'
>   config.ru:1:in `<main>'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:112:in`eval'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:112:in `preload_app'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:158:in`module:App'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
>   /opt/redmine-2.6.1-1/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.57/helper-scripts/rack-preloader.rb:28:in`<main>'

**Comment by sunnycomes** [comment]
I know where is the problem. My redmine(2.6.1stable) has supported markdown text formatting.
